// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that enhances hostel room descriptions using uploaded photos, GPS location, nearby landmarks, amenities, and room features.
 *
 * - enhanceHostelDescription - A function that enhances the hostel description.
 * - EnhanceHostelDescriptionInput - The input type for the enhanceHostelDescription function.
 * - EnhanceHostelDescriptionOutput - The return type for the enhanceHostelDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceHostelDescriptionInputSchema = z.object({
  photosDataUris: z
    .array(z.string())
    .describe(
      "Photos of the hostel room, as data URIs that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  gpsLocation: z
    .string()
    .describe('The GPS location of the hostel (latitude, longitude).'),
  nearbyLandmarks: z.string().describe('Nearby landmarks to the hostel.'),
  amenities: z.string().describe('Amenities offered by the hostel.'),
  roomFeatures: z.string().describe('Features of the room (e.g., number of beds, bathroom details).'),
  currentDescription: z.string().describe('The current description of the hostel room.'),
});
export type EnhanceHostelDescriptionInput = z.infer<
  typeof EnhanceHostelDescriptionInputSchema
>;

const EnhanceHostelDescriptionOutputSchema = z.object({
  enhancedDescription: z.string().describe('The enhanced description of the hostel room.'),
});
export type EnhanceHostelDescriptionOutput = z.infer<
  typeof EnhanceHostelDescriptionOutputSchema
>;

export async function enhanceHostelDescription(
  input: EnhanceHostelDescriptionInput
): Promise<EnhanceHostelDescriptionOutput> {
  return enhanceHostelDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceHostelDescriptionPrompt',
  input: {schema: EnhanceHostelDescriptionInputSchema},
  output: {schema: EnhanceHostelDescriptionOutputSchema},
  prompt: `You are an expert copywriter specializing in writing compelling descriptions for hostel rooms.  Your goal is to attract more potential students with an informative and engaging listing.

  Here's the information you have about the hostel room:

  Current Description: {{{currentDescription}}}
  GPS Location: {{{gpsLocation}}}
  Nearby Landmarks: {{{nearbyLandmarks}}}
  Amenities: {{{amenities}}}
  Room Features: {{{roomFeatures}}}

  Photos:
  {{#each photosDataUris}}
  {{media url=this}}
  {{/each}}

  Rewrite the description to be more attractive and informative, highlighting the key features and benefits for students.  Focus on creating a vivid and appealing picture of what it's like to stay in this room.
  Rewrite the description to be no more than 200 words.
  Do not mention that the description was written by an AI.
  `,
});

const enhanceHostelDescriptionFlow = ai.defineFlow(
  {
    name: 'enhanceHostelDescriptionFlow',
    inputSchema: EnhanceHostelDescriptionInputSchema,
    outputSchema: EnhanceHostelDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
